---
- block:

    - name: setup apt repository
      apt_repository:
        repo: "deb http://repo.steampowered.com/steam/ precise steam"
        filename: valve-steam
      when:
        - ansible_os_family == "Debian"

    - name: install steam
      package:
        name: "steam"
        state: present

  become: yes
  become_user: root
  tags:
    - valve-steam
